/*
 * Copyright (C) 2013, 2014 beamproject.org
 *
 * This file is part of beam-common.
 *
 * beam-common is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * beam-common is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.beamproject.common;

import java.security.PublicKey;

public enum MessageField {

    /**
     * Stands for "Version". This field contains the message format version.
     */
    VRS("VRS"),
    /**
     * Stands for "Participant" and is the pubilc key (X.509 encoded) of the
     * target {@link Participant} of this message.
     */
    PRT("PRT"),
    /**
     * Stands for "Content" and contains the message as several sub fields.
     */
    CNT("CNT"),
    /**
     * This field is a part of the Challenge-Response protocol. This protocol
     * allows to establish a long-time session.
     * <p>
     * {@code CRPHASE} stands for "Challenge Response Phase" and informs the
     * recipient of the message about the current phase in the protocol.
     */
    CNT_CRPHASE("CRSPHASE"),
    /**
     * This field is a part of the Challenge-Response protocol. This protocol
     * allows to establish a long-time session.
     * <p>
     * {@code CRPUBKEY} stands for "Challenge Response Public Key" and contains
     * the senders {@link PublicKey} (as byte array).
     */
    CNT_CRPUBKEY("CRPUBKEY"),
    /**
     * This field is a part of the Challenge-Response protocol. This protocol
     * allows to establish a long-time session.
     * <p>
     * {@code CRNONCE} stands for "Challenge Response Nonce" and a nonce
     * (=number used once), generated by the sender.
     */
    CNT_CRNONCE("CRNONCE"),
    /**
     * This field is a part of the Challenge-Response protocol. This protocol
     * allows to establish a long-time session.
     * <p>
     * {@code CRSIG} stands for "Challenge Response Signature" and contains the
     * signature, created with the other sides private key.
     */
    CNT_CRSIG("CRSIG"),
    /**
     * Stands for "Message" and contains the message text itself.
     */
    CNT_MSG("MSG");

    private final String value;

    private MessageField(String value) {
        this.value = value;
    }

    /**
     * Returns the beam format code. For example, {@code PRM_KEY} results in
     * {@code KEY}, which can be used in a {@code PRM} field.
     *
     * @return The protocol field identifier.
     */
    @Override
    public String toString() {
        return value;
    }
}
